### ISSUE TITLE
Error: BaseConfig: 	Environment key "[object Object]" is unknown

### ISSUE THREAD

**Issue by rushi** [Spence-S/vscode-linter-xo#7]
The "XO: Fix all auto-fixable problems" doesn't work. 

I have a custom config in `.xo-config.json`. From the logs, it looks like it picks up the rules because I see this _(config formatted by me for readability)_:
```
[Info  - 8:57:39 PM] Linting /Users/foo/app/src/components/SellerPage/Page.jsx With Options {
    "options": {
        "rules": {
            "node/file-extension-in-import": 0,
            "import/extensions": 0,
            "capitalized-comments": 0,
            "no-warning-comments": 0,
            "unicorn/filename-case": ["error", { "cases": { "camelCase": true, "pascalCase": true } }],
            "react/boolean-prop-naming": ["error", { "rule": "^(is|has|should)[A-Z]([A-Za-z0-9]?)+" }],
            "max-params": ["error", 6],
            "unicorn/prevent-abbreviations": [
                "error",
                { "replacements": { "param": false, "params": false, "props": false } }
            ],
            "no-implicit-coercion": ["error", { "boolean": false }]
        },
        "settings": {},
        "globals": [],
        "envs": [{ "jest/globals": true }],
        "plugins": ["jest"],
        "extends": [],
        "nodeVersion": ">=14",
        "cwd": "/Users/foo/app",
        "filename": "/Users/foo/app/src/components/SellerPage/Page.jsx",
        "filePath": "/Users/foo/app/src/components/SellerPage/Page.jsx",
        "extensions": ["js", "jsx", "mjs", "cjs", "ts", "tsx"],
        "ignores": [
            "**/node_modules/**",
            "**/bower_components/**",
            "flow-typed/**",
            "coverage/**",
            "{tmp,temp}/**",
            "**/*.min.js",
            "vendor/**",
            "dist/**",
            "tap-snapshots/*.{cjs,js}"
        ]
    },
    "prettierOptions": {}
}

```

But then immediately after that I see this:
```
[Error - 8:57:40 PM] Error: BaseConfig:
	Environment key "[object Object]" is unknown

[Error - 8:57:40 PM] BaseConfig:
	Environment key "[object Object]" is unknown

[Error - 8:57:40 PM] Error: BaseConfig:
	Environment key "[object Object]" is unknown

   at /Users/foo/app/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:175:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/Users/foo/app/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:169:34)
    at ConfigValidator.validateConfigArray (/Users/foo/app/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:319:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/foo/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/foo/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at CLIEngine.isPathIgnored (/Users/foo/app/node_modules/eslint/lib/cli-engine/cli-engine.js:973:18)
    at ESLint.isPathIgnored (/Users/foo/app/node_modules/eslint/lib/eslint/eslint.js:688:26)
    at Object.lintText (file:///Users/foo/app/node_modules/xo/index.js:126:20)
    at tc.runLint (/Users/rushi/.vscode/extensions/spence-s.linter-xo-3.0.1/dist/server.js:46:6804)
```

**Comment by Spence-S** [comment]
@rushi is the xo cli able to work here? I suspect its `"envs": [{ "jest/globals": true }],` in your config. You need to pass that as just a string to xo - like: `"envs": ["jest"]` xo should take care of the rest. If you're already doing that let me know and Ill investigate further.
